module.exports = {
  WonderNames: [
    "Ephesos",
    "Gizah",
    "Olympia",
    "Alexandria",
    "Rhodos",
    "Babylon",
    "Halikarnassos",
    "Petra",
    "Byzantium",
    "Siracusa",
    "Roma",
    "Abu Simbel",
  ],
  Modes: ["Day", "Night"],
  PointFieldsSimple: [
    { variable: "wonder", label: "Wonder" },
    { variable: "money", label: "Money" },
    { variable: "red", label: "Red" },
    { variable: "blue", label: "Blue" },
    { variable: "yellow", label: "Yellow" },
    { variable: "green", label: "Green" },
    { variable: "purple", label: "Purple" },
    { variable: "black", label: "Black" },
    { variable: "white", label: "White" },
    { variable: "armada0", label: "Armada0" },
    { variable: "armada1", label: "Armada1" },
  ],
  PointFieldsFancy: [
    { variable: "wonder", label: "Wonder" },
    { variable: "money", label: "Wealth" },
    { variable: "red", label: "Military" },
    { variable: "blue", label: "Monuments" },
    { variable: "yellow", label: "Trade" },
    { variable: "green", label: "Infrastructure" },
    { variable: "purple", label: "Academia" },
    { variable: "black", label: "Underworld" },
    { variable: "white", label: "Leaders" },
    { variable: "armada0", label: "Naval Battles" },
    { variable: "armada1", label: "Harbour" },
  ],
  DefaultValues: {
    wonder_name: "",
    wonder_mode: "",
    wonder: "",
    money: "",
    red: "",
    blue: "",
    yellow: "",
    green: "",
    purple: "",
    black: "",
    white: "",
    armada0: "",
    armada1: "",
    sum: "",
  },
};
