module.exports = {
  ScoresDefault: [
    {
      player_name: "",
      wonder_name: "",
      wonder_mode: "",
      sc_wonder: "",
      sc_money: "",
      sc_red: "",
      sc_blue: "",
      sc_yellow: "",
      sc_green: "",
      sc_purple: "",
      sc_black: "",
      sc_white: "",
      sc_armada0: "",
      sc_armada1: "",
      sum: "",
    },
  ],
  WonderNames: [
    "Ephesos",
    "Gizah",
    "Olympia",
    "Alexandria",
    "Rhodos",
    "Babylon",
    "Halikarnassos",
    "Petra",
    "Byzantium",
    "Siracusa",
    "Roma",
    "Abu Simbel",
  ],
  Modes: ["Day", "Night"],
  PointFieldsSimple: [
    { variable: "wonder", label: "Wonder" },
    { variable: "money", label: "Money" },
    { variable: "red", label: "Red" },
    { variable: "blue", label: "Blue" },
    { variable: "yellow", label: "Yellow" },
    { variable: "green", label: "Green" },
    { variable: "purple", label: "Purple" },
    { variable: "black", label: "Black" },
    { variable: "white", label: "White" },
    { variable: "armada0", label: "Armada 0" },
    { variable: "armada1", label: "Armada 1" },
  ],
  PointFieldsFancy: [
    { variable: "wonder", label: "Wonder" },
    { variable: "money", label: "Wealth" },
    { variable: "red", label: "Military" },
    { variable: "blue", label: "Monuments" },
    { variable: "yellow", label: "Trade" },
    { variable: "green", label: "Infrastructure" },
    { variable: "purple", label: "Academia" },
    { variable: "black", label: "Underworld" },
    { variable: "white", label: "Leaders" },
    { variable: "armada0", label: "Naval Battles" },
    { variable: "armada1", label: "Harbour" },
  ],
  DefaultValues: {
    player_name: "",
    wonder_name: "",
    wonder_mode: "",
    sc_wonder: "",
    sc_money: "",
    sc_red: "",
    sc_blue: "",
    sc_yellow: "",
    sc_green: "",
    sc_purple: "",
    sc_black: "",
    sc_white: "",
    sc_armada0: "",
    sc_armada1: "",
    sum: "",
  },
};
